name: sopan_santun_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  animations: ^2.0.11
  carousel_slider: ^5.1.1
  expandable_cardview: ^1.1.0
  expansion_tile_card: ^3.0.0
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_expandable_fab: ^2.0.0
  flutter_form_builder: ^10.0.1
  flutter_localizations:
    sdk: flutter
  flutter_staggered_animations: ^1.1.1
  font_awesome_flutter: ^10.7.0
  form_builder_validators: ^11.2.0
  get: ^4.6.5
  google_fonts: ^6.1.0
  image_picker: ^1.1.1
  intl: ^0.20.2
  lottie: ^3.1.0
  modal_bottom_sheet: ^3.0.0
  path: ^1.9.1
  path_provider: ^2.1.2
  pdf: ^3.10.4
  printing: ^5.11.0
  provider: ^6.1.4
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  sqflite: ^2.4.2
  url_launcher: ^6.2.5
  firebase_analytics: ^12.0.3
  firebase_auth: ^6.1.1
  firebase_core: ^4.2.0
  google_sign_in: ^6.1.5

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  shared_preferences: ^2.0.15

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/animations/loading.json
  # fonts:
  #   - family: ComicNeue
  #     fonts:
  #       - asset: assets/fonts/ComicNeue-Regular.ttf
  #   - family: NotoSans
  #     fonts:
  #       - asset: assets/fonts/Noto/NotoSans-Regular.ttf
  #   - family: NotoEmoji
  #     fonts:
  #       - asset: assets/fonts/Noto/NotoColorEmoji.ttf
